name: CI/CD Pipeline

on:
  push:
    branches:
      - CAT-66-GROZ

jobs:
  build-and-push:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.YA_TOKEN_REGISTRY }}

      - name: Build and push client image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.client
          push: true
          tags: cr.yandex/${{ vars.ID_REGISTRY }}/${{ github.repository_owner }}/${{ github.event.repository.name }}/client:${{ github.ref_name }}
          build-args: |
            CLIENT_HOST=${{ vars.CLIENT_HOST }}
