name: Автодеплой

on:
  push:
    branches:
      - CAT-66-GROZ

jobs:
  build-and-push:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Подключение репозитория
        uses: actions/checkout@v2

#      - name: Авторизация в реестре докер-контейнеров
#        uses: docker/login-action@v3
#        with:
#          registry: cr.yandex
#          username: oauth
#          password: ${{ secrets.YA_TOKEN_REGISTRY }}
#
#      - name: Сборка и отправка образа приложения "client"
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: Dockerfile.client
#          push: true
#          tags: cr.yandex/${{ vars.ID_REGISTRY }}/${{ github.event.repository.name }}/client:prod
#          build-args: |
#            CLIENT_HOST=${{ vars.CLIENT_HOST }}
#
#      - name: Сборка и отправка образа приложения "server"
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: Dockerfile.server
#          push: true
#          tags: cr.yandex/${{ vars.ID_REGISTRY }}/${{ github.event.repository.name }}/server:prod

  deploy:
    needs: build-and-push
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Подключение репозитория
        uses: actions/checkout@v2

      - name: Вывести имя пользователя
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: whoami

      - name: Копирование docker-compose-prod.yml на сервер
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: docker-compose-prod.yml
          target: /home/admin
